apiVersion: v1
kind: Service
metadata:
  name: kubia-service
  labels:
    run: kubia
spec:
  selector:
    app: kubia
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080