apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    run: nginx
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080